### ISSUE TITLE
Failed to load or decode Blob.

### ISSUE THREAD

**Issue by mengshouer** [Sec-ant/barcode-detector#41] opened 2023-11-24 17:18 UTC
I created a minimum instance like in the [example](https://github.com/Sec-ant/barcode-detector#example) to run.

I use esbuild-register run the code

then it throws DOMException [InvalidStateError]: Failed to execute 'detect' on 'BarcodeDetector': Failed to load or decode Blob. 
![image](https://github.com/Sec-ant/barcode-detector/assets/36481080/aa97fefe-a0a5-467c-943f-ada56ff5e1fc)

```js
// package.json
{
  "name": "barcode",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "start": "node -r esbuild-register index.ts"
  },
  "author": "",
  "devDependencies": {
    "esbuild": "^0.19.7",
    "esbuild-register": "^3.5.0",
    "typescript": "^5.3.2"
  }
}
```

```js
// tsconfig.json
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "commonjs",
    "skipLibCheck": true,
    "moduleResolution": "node"
  },
  "include": ["."]
}
```

**Comment by Sec-ant** [comment] 2023-11-24 17:33
I don't think this package will fully work on nodejs because it relies on some DOM APIs. This package is intended for browsers.

However this issue is caused by some mistake I made [here (Reference Errors)](https://github.com/Sec-ant/barcode-detector/blob/62ffcd2140609e27845d7fccd9b49aa249a53c44/src/utils.ts#L240-L266) and it will be fixed soon. Thanks for raising this issue.

**Closed** 2023-11-25 04:45 UTC
Labels: bug

**Comment by Sec-ant** [comment] 2023-11-25 05:02
Hello, v2.1.3 fixed this error message. But as I said this package is intended for browsers so it still won't work in node because `DOMRectReadOnly` is a DOM API and it is specified in the spec https://wicg.github.io/shape-detection-api/#detectedbarcode-section.

If you don't need a spec-compliant barcode detector and want a solution in node, check out [`zxing-wasm`].(https://github.com/Sec-ant/zxing-wasm)

**Comment by mengshouer** [comment] 2023-11-25 05:19
> Hello, v2.1.3 fixed this error message. But as I said this package is intended for browsers so it still won't work in node because `DOMRectReadOnly` is a DOM API and it is specified in the spec [wicg.github.io/shape-detection-api/#detectedbarcode-section](https://wicg.github.io/shape-detection-api/#detectedbarcode-section).
> 
> If you don't need a spec-compliant barcode detector and want a solution in node, check out [`zxing-wasm`](https://github.com/Sec-ant/zxing-wasm)

I have already tried zxing-wasm before, but there will be errors when I run it after building it, tsconfig like above

error like:

[ERR_REQUIRE_ESM]: require() of ES Module D:\path\to\node_modules\zxing-wasm\dist\full\index.js from D:\path\to\barcodeDecoder\lib\index.js not supported.


Instead change the require of  D:\path\to\node_modules\zxing-wasm\dist\full\index.js in D:\path\to\barcodeDecoder\lib\index.js  to a dynamic 'import("zxing-wasm")' which is available in all CommonJS modules
