### ISSUE TITLE
Barcode detection service unavailable

### ISSUE THREAD

**Issue by louie0086** [Sec-ant/barcode-detector#18] opened 2023-09-15 03:09 UTC
https://github.com/Sec-ant/barcode-detector/blob/ab876a6a19b610ed3ce4b69f8216ed3c878421f4/src/BarcodeDetector.ts#L140-L143

i used vue-qrcode-reader at https website

```html
<qrcode-stream @detect="onDetect"></qrcode-stream>
```

it shows `"Barcode detection service unavailable. Use 'setZXingModuleOverrides' in offline or strict CSP environments.",
          "NotSupportedError"`

the host already set `Strict-Transport-Security:
max-age=31536000; includeSubdomains; preload
`

but the static js file not set

i see the demo website https://vue-qrcode-reader.netlify.app. it's doc and static js both set Strict-Transport-Security

how can i solve the detect error?

**Comment by Sec-ant** [comment] 2023-09-15 03:49
Hey, louie

I don't think `Strict-Transport-Security` is relevant here. "CSP" is short for "[Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy)".

This package uses [WebAssembly](https://developer.mozilla.org/en-US/docs/WebAssembly) to provide the core function of detecting barcodes. And the browser must instantiate and execute the WebAssembly module to use it. However, per the spec, websites can control whether to block the WebAssembly execution by setting the [`script-src` directive in CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_webassembly_execution), specifically the `wasm-unsafe-eval` or `unsafe-eval` source value. If it is blocked, the error `Barcode detection service unavailable` will thrown.

Another possible reason for this error is the network connectivity. To prevent bloating the size, this package will load the `.wasm` file from the `cdn.jsdelivr.net` CDN at runtime. If this connection is somewhat get blocked, the `service unavailable` error will also be thrown.

There're corresponding ways in which you can solve this problem:

- If you have control on the website where you're using this package, you can modify the CSP of the site to allow `wasm-unsafe-eval`.
- If this is a connectivity issue or you don't want to load the `.wasm` file from a CDN. You can use `setZXingModuleOverrides` exported by `vue-qrcode-reader` to change the location where the `.wasm` file is hosted. For example, you can host the file on your website as an asset.

If neither solves your problem, it would be great if you can provide the malfunctioning website so that I can dig into it and check whether there're some other bugs to fix.

**Comment by louie0086** [comment] 2023-09-15 05:53
```ts
import wasmFile from "../node_modules/@sec-ant/zxing-wasm/dist/reader/zxing_reader.wasm?url";
```
I would like to ask what the syntax (?url)is?

in vue-cli project

```js
import wasmFile from "@sec-ant/zxing-wasm/dist/reader/zxing_reader.wasm?url";
```

it's show error:

```
* a in ./node_modules/@sec-ant/zxing-wasm/dist/reader/zxing_reader.wasm?url

To install it, you can run: npm install --save a
```

How do I import the wasm module correctly?

**Comment by Sec-ant** [comment] 2023-09-15 07:23
Ok you decide not to fetch the `.wasm` file from jsDelivr. There're some gotchas, so I'd like to explain more:

---

**First, a question: I wonder if you want to inline the `.wasm` file inside your script output files or you want to host it as a binary file on your site, and fetch it from your site at runtime?**

### Inline

Inlining means encoding the `.wasm` file as a Base64 data url and hardcode this data url inside your script files. If you use a syntax like this: 
```
import wasmFile from "...?url"
```
then you're inlining it. `?url` is a syntax provided by build tools, like Vite, to transform assets into data urls. I'm not sure if `vue-cli` supports it. If it is supported, then the `wasmFile` will be a huge base64 encoded data url.

Afterwards, you use `setZXingModuleOverrides` + `locateFile` to relocate the fetching path to this data url:

```ts
setZXingModuleOverrides({
  locateFile: (path, prefix) => {
    if (path.endsWith(".wasm")) {
      return wasmFile; // <= a huge Base64 encoded data url
    }
    return prefix + path;
  },
});
```

A data url occupies a larger space than its binary form, and parsing a data url into binary data also consumes more CPU clocks. So, ideally, I suggest you to not use the inline form.

### Binary

If you want to host it as a binary file on your site, then you need not to import it. You can just copy the `.wasm` file to your website's assets folder, e.g. `public` or `assets`, and use `setZXingModuleOverrides` + `locateFile` to relocate the fetching path like this:

```ts
setZXingModuleOverrides({
  locateFile: (path, prefix) => {
    if (path.endsWith(".wasm")) {
      return "https://<your website host>/public/zxing_reader.wasm"; // <= where the .wasm file is at
    }
    return prefix + path;
  },
});
```

Either way, CSP still applies. You have to make sure `content-src` and `script-src` are correctly configured to allow you fetching and executing it.

---

**Second question: where is the `.wasm` file?**

Normally, when you add `vue-qrcode-reader` as a dependency in your project, it will also download its dependencies inside `node_modules` folder, which includes `barcode-detector`. And `barcode-detector` in turn will download its dependency `@sec-ant/zxing-wasm`. This process is handled by the package manager automatically so you don't need to worry.

The `.wasm` file is published as an asset included in the package `@sec-ant/zxing-wasm`, therefore, the `.wasm` file can be found at this path:
```
<project root>/node_modules/@sec-ant/zxing-wasm/dist/reader/zxing_reader.wasm
```

**BUT**, I made a mistake not pinning the version. So, the `.wasm` file you found in `<project root>/node_modules/@sec-ant/zxing-wasm` may not be what `vue-qrcode-reader` expects (Sorry for this mistake, I'm going to fix this in the next version). Therefore, for now, I recommend you manually download the `.wasm` file with the correct version, from the CDN.

If you're using [`vue-qrcode-reader@v5.3.4`](https://github.com/gruhn/vue-qrcode-reader/releases/tag/v5.3.4), the matching version is `@sec-ant/zxing-wasm@2.1.3`, so you can download the `zxing_reader.wasm` file from any of the following CDN paths:
- UNPKG: https://unpkg.com/@sec-ant/zxing-wasm@2.1.3/dist/reader/zxing_reader.wasm
- jsDelivr: https://cdn.jsdelivr.net/npm/@sec-ant/zxing-wasm@2.1.3/dist/reader/zxing_reader.wasm
- Skypack: https://cdn.skypack.dev/@sec-ant/zxing-wasm@2.1.3/dist/reader/zxing_reader.wasm

Once you've downloaded the correct version of the `.wasm` file, you can inline or host it as you wish in your project.

Again, I'm really sorry for the inconvenience. Once the version problem is fixed and released in `vue-qrcode-reader`, you won't have to worry about downloading it with the matching version. You can just import or copy it from `<project root>/node_modules/@sec-ant/zxing-wasm/dist/reader/zxing_reader.wasm`.

**Comment by louie0086** [comment] 2023-09-15 07:56
Thank @Sec-ant 

i just put `zxing_reader.wasm` at assets public folder and then

```js
  setZXingModuleOverrides({
    locateFile: (path, prefix) => {
      if (path.endsWith(".wasm")) {
        
        return '/zxing_reader.wasm';
      }
      return prefix + path;
    },
  });
```

my project site can request zxing_reader.wasm now.but it's still has error `"Barcode detection service unavailable. Use 'setZXingModuleOverrides' in offline or strict CSP environments."`

if the `zxing_reader.wasm` not from CDN and CSP not configured .Is this error still here?

**Comment by Sec-ant** [comment] 2023-09-15 08:16
Then this may be some other bug. To solve this problem I'll need more information.

- **If this issue is OS/browser related**

  For example, is the demo page of vue-qrcode-reader works on the same device? If it doesn't, then it's probably device related, and then I need the versions of the device's OS and browser.

- **If the error only occurs in your project site**

  Then it would be very helpful for you to share a repo to let me reproduce this problem, or share your site so that I can debug.

**Comment by louie0086** [comment] 2023-09-15 08:34
> Then this may be some other bug. To solve this problem I'll need more information.
> 
> * **If this issue is OS/browser related**
>   For example, is the [demo page of vue-qrcode-reader](https://vue-qrcode-reader.netlify.app/demos/) works on the same device? If it doesn't, then it's probably device related, and then I need the versions of the device's OS and browser.
> * **If the error only occurs in your project site**
>   Then it would be very helpful for you to share a repo to let me reproduce this problem, or share your site so that I can debug.

yes.same device. vue-qrcode-reader demo page no exception

**Comment by Sec-ant** [comment] 2023-09-15 08:38
In that case, can you share a repro :)

**Comment by louie0086** [comment] 2023-09-15 08:56
> In that case, can you share a repro :)

Ok .i send email to you

**Comment by Sec-ant** [comment] 2023-09-15 09:38
> Ok .i send email to you

Alright, here's my email address: zzwu@zju.edu.cn

**Comment by Sec-ant** [comment] 2023-09-17 09:45
@louie0086 Can you try `vue-qrcode-reader@5.3.5` (matches with `@sec-ant/zxing-wasm@2.1.5`) and see if this error still exists? If the error still exists, can you find more error information in the console?

**Comment by louie0086** [comment] 2023-09-19 01:32
> @louie0086 Can you try `vue-qrcode-reader@5.3.5` (matches with `@sec-ant/zxing-wasm@2.1.5`) and see if this error still exists? If the error still exists, can you find more error information in the console?

i updated @sec-ant/zxing-wasm@2.1.5 and copy zxing_reader.wasm to zxing_reader1.wasm 

still 

```
  setZXingModuleOverrides({
    locateFile: (path, prefix) => {
      if (path.endsWith(".wasm")) {
        
        return '/zxing_reader1.wasm';
      }
      return prefix + path;
    },
  });
```

now it show 

```
    "Barcode detection service unavailable.",
    "NotSupportedError"
```

**Comment by Sec-ant** [comment] 2023-09-19 02:10
I added this line of code to log a detailed error information, can you some how see this in the console?

https://github.com/Sec-ant/barcode-detector/blob/bca5f666062e29a8a4d075f71e4695f9e7fc77c1/src/BarcodeDetector.ts#L156-L157

**Comment by louie0086** [comment] 2023-09-19 10:01
> I added this line of code to log a detailed error information, can you some how see this in the console?
> 
> https://github.com/Sec-ant/barcode-detector/blob/bca5f666062e29a8a4d075f71e4695f9e7fc77c1/src/BarcodeDetector.ts#L156-L157

![image](https://github.com/Sec-ant/barcode-detector/assets/145084444/ea2da55f-a693-4905-ae36-536cbfd13f91)

**Comment by Sec-ant** [comment] 2023-09-19 10:27
> > I added this line of code to log a detailed error information, can you some how see this in the console?
> > 
> > https://github.com/Sec-ant/barcode-detector/blob/bca5f666062e29a8a4d075f71e4695f9e7fc77c1/src/BarcodeDetector.ts#L156-L157
> 
> ![image](https://github.com/Sec-ant/barcode-detector/assets/145084444/ea2da55f-a693-4905-ae36-536cbfd13f91)
> 

The RangeError is what we've been seeking. Is that just an empty object or does it hold more information?

**Comment by louie0086** [comment] 2023-09-20 08:17
> <img alt="screenshot" width="645" src="https://user-images.githubusercontent.com/10386119/268953144-2bafbe11-9042-4612-b823-a718756e1442.png">
> The RangeError is what we've been seeking. Is that just an empty object or does it hold more information?

message:Range consisting of offset and length are out of bounds.

**Comment by Sec-ant** [comment] 2023-09-20 08:36
Hmm, interesting.

If this is something about the WebAssembly instantiation, I wonder why `vue-qrcode-reader` demo page works.

Does this error message have a context so that I can check which line of code and file this error is thrown from? Or can you jump to the corresponding file and provide some information on its whereabouts? Screenshots would be great, and you can email me if you want.

PS: I previously said
> Once the version problem is fixed and released in vue-qrcode-reader, you won't have to worry about downloading it with the matching version. You can just import or copy it from <project root>/node_modules/@sec-ant/zxing-wasm/dist/reader/zxing_reader.wasm.

The good news is, starting from `vue_qrcode_reader@5.3.5`, this version problem is fixed :).

**Comment by louie0086** [comment] 2023-09-21 08:29
I isolated a stripped down code from my project that is scannable. But the original project still has Range Error and NotSupportedError.

https://github.com/louie0086/test_Barcode

**Comment by Sec-ant** [comment] 2023-09-21 08:46
Thanks for the repo, but I'm afraid a scannable demo can't provide to too much information on why your original project doesn't work.

What about these questions I previously asked:

> Does this error message have a context so that I can check which line of code and file this error is thrown from? Or can you jump to the corresponding file and provide some information on its whereabouts?

**Comment by louie0086** [comment] 2023-09-22 02:28
RangeError stack here:

https://github.com/louie0086/test_Barcode/blob/5c7a69936a4649c5b860b405b6797ba5aef3456c/public/barcode-detector/dist/es/pure.js#L345-L354

**Comment by Sec-ant** [comment] 2023-09-22 03:20
> RangeError stack here:
> 
> https://github.com/louie0086/test_Barcode/blob/5c7a69936a4649c5b860b405b6797ba5aef3456c/public/barcode-detector/dist/es/pure.js#L345-L354
> 
> ```js
>  $.HEAP8.set(O, L)
> ```

Thanks, this is very helpful. So the error is thrown from this line from the source code:

https://github.com/Sec-ant/zxing-wasm/blob/8b8df68e781e7524ce96f12276c7a028b2c0c9d6/src/core.ts#L390

I'm not very clear about the root cause but I can try to do some debugging. So this error happens on an iPhone iOS 16.6 Safari Browser, right?

**Comment by louie0086** [comment] 2023-09-22 03:24
> > RangeError stack here:
> > https://github.com/louie0086/test_Barcode/blob/5c7a69936a4649c5b860b405b6797ba5aef3456c/public/barcode-detector/dist/es/pure.js#L345-L354
> > ```js
> >  $.HEAP8.set(O, L)
> > ```
> 
> Thanks, this is very helpful. So the error is thrown from this line from the source code:
> 
> https://github.com/Sec-ant/zxing-wasm/blob/8b8df68e781e7524ce96f12276c7a028b2c0c9d6/src/core.ts#L390
> 
> I'm not very clear about the root cause but I can try to do some debugging. So this error happens on an iPhone iOS 16.6 Safari Browser, right?

yes.iPhone 14 Pro Max

**Comment by Sec-ant** [comment] 2023-09-22 04:27
Can you log the `data`, `byteLength`, `bufferPtr` and `HEAP8` if you can patch the source packages in your project?

![image](https://github.com/Sec-ant/barcode-detector/assets/10386119/8f1123ef-e7af-40cf-b789-a49f64e2220b)

You can also directly modify the dist file, like this:

![image](https://github.com/Sec-ant/barcode-detector/assets/10386119/66c998b5-585e-4420-b801-b3b6507f3129)

And show me the result?

**Comment by louie0086** [comment] 2023-09-25 01:28
![img_v2_b4a0580b-329e-45fc-a828-4353af1f5chu](https://github.com/Sec-ant/barcode-detector/assets/145084444/2e6147a6-c326-4bd1-bfd8-9376c1930df6)

**Comment by Sec-ant** [comment] 2023-09-25 02:24
What's the `byteLength` of the `Int8Array`, i.e. `zxingInstance.HEAP8.byteLength`?

**Comment by louie0086** [comment] 2023-09-25 02:32
> `byteLength`

i just console at barcode-detector.pure.js

```js
    const w = await Bt($, ot.getState().zxingModuleOverrides),
      {
        data: O,
        width: G,
        height: j,
        data: { byteLength: F },
      } = c,
      Y = w._malloc(F)
    console.log('data:',O)
    console.log('byteLength:',F)
    console.log('bufferPtr:',Y)
    console.log('zxingInstance.HEAP8:',w.HEAP8)
    w.HEAP8.set(O, Y)
    const N = w.readBarcodesFromPixmap(Y, G, j, m, pe(u), g)
    w._free(Y)
```

**Comment by Sec-ant** [comment] 2023-09-25 02:38
I mean, can you also log the `byteLength` of the `HEAP8` object in the console? So I can know the total available memory it holds.

like this (add this line):

```js
console.log('zxingInstance.HEAP8.byteLength:', w.HEAP8.byteLength);
```

**Comment by louie0086** [comment] 2023-09-28 07:25
> ```js
> w.HEAP8.byteLength
> ```

the result: `zxingInstance.HEAP8.byteLength:0`

**Comment by Sec-ant** [comment] 2023-09-28 07:37
That's some useful info and a good start. Apparently, for some reason, the memory is not successfully allocated, which brings us to this line of code:

https://github.com/louie0086/test_Barcode/blob/5c7a69936a4649c5b860b405b6797ba5aef3456c/public/barcode-detector/dist/es/pure.js#L415-L416

Can you help me check whether `J.buffer.byteLength` is also zero?

**Comment by louie0086** [comment] 2023-09-29 02:16
> That's some useful info and a good start. Apparently, for some reason, the memory is not successfully allocated, which brings us to this line of code:
> 
> https://github.com/louie0086/test_Barcode/blob/5c7a69936a4649c5b860b405b6797ba5aef3456c/public/barcode-detector/dist/es/pure.js#L415-L416
> 
> Can you help me check whether `J.buffer.byteLength` is also zero?

https://github.com/louie0086/test_Barcode/blob/master/barcode-detector.pure_4.js#L443

K.buffer  undefiend

**Comment by Sec-ant** [comment] 2023-09-29 02:57
Hmmm, that means `wasmMemory` is not initiated.

Can you log `n`, `n.exports` and `n.exports.qa` in this function before the `return` statement?

https://github.com/louie0086/test_Barcode/blob/2faebca6c2e0ed3626b7ebfa183937b76cc279fe/barcode-detector.pure_4.js#L564-L566

**Comment by louie0086** [comment] 2023-09-29 06:03
![20230929-140203](https://github.com/Sec-ant/barcode-detector/assets/145084444/006a7521-ee87-452e-bde8-596d1d13ba0e)
![20230929-140207](https://github.com/Sec-ant/barcode-detector/assets/145084444/56411543-9579-44eb-92a5-65f3e4289541)

https://github.com/louie0086/test_Barcode/blob/f1834f83f809259f7038b52557df0a9f3df58d93/barcode-detector.pure_4.js#L564-L566

**Comment by Sec-ant** [comment] 2023-09-30 15:04
In a normal case, the `n.exports.qa` should be an instance of [`WebAssembly.Memory`](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Memory), like this (in a chrome browser):

![image](https://github.com/Sec-ant/barcode-detector/assets/10386119/56831d8d-31b4-44cc-9b8d-5bff71b843ff)

I cannot tell whether `B$()` in your snapshot is an instance of the `WebAssembly.Memory` or is just a plain function. Given that the code works in your demo repo but not in your project, can you also check the `n.exports.qa` in your demo repo and compare the working one with the error one to see if the difference indeed lies in the `n.exports.qa`?

**Comment by louie0086** [comment] 2023-10-03 05:16
https://github.com/louie0086/test_Barcode/blob/master/barcode-detector.pure_4.js#L564-L566

i add a `alert`

The demo tips `[object WebAssembly.Memory]`

but the project is `function B$(){hC()}`

**Comment by Sec-ant** [comment] 2024-08-21 10:23
I'll close this for now as this is not reproducible. Feel free to request a reopen if anyone can provide a reliable reproduction.

**Closed by Sec-ant** 2024-08-21 10:23 UTC
Labels: question

**Comment by crazyrabbit0** [comment] 2024-11-29 10:48
I get this weird error, similar to the above:
```
NotSupportedError: Failed to execute 'detect' on 'BarcodeDetector': Barcode detection service unavailable
```

I use Vue 3 with Vite 5:
1. When I use a build without any options _(all assets imported separately)_, I get the above error.
2. When I use the build options to inline my assets into a single .js file, no errors occur.

It's not really a problem since I can solve it with the second method, but I just thought you should know.

The way I import it in the code is this:
```
import wasmFile from '@/../node_modules/zxing-wasm/dist/reader/zxing_reader.wasm?url'
    setZXingModuleOverrides({
        locateFile: (path, prefix) => {
            if (path.endsWith('.wasm')) {
                return wasmFile
            }
            return prefix + path
        },
    })
```

**Comment by Sec-ant** [comment] 2024-11-29 14:49
@crazyrabbit0 Hi, is it possible that you provide a minimal reproduction repo?

**Comment by crazyrabbit0** [comment] 2024-11-30 16:55
Sure, here you go, it's quite basic really:
https://github.com/crazyrabbit0/TestVueQrcode

Mind the fact, that when I build it locally it works fine, even with separate asset files,
but when I push it to the AWS server, I get the error mentioned above.

**Comment by Sec-ant** [comment] 2024-12-01 03:45
@crazyrabbit0 hmm, as you said, the demo project works properly in local. I don't have an aws account so I tried to deploy the dist folder to a [netlify site](https://tranquil-daffodil-325564.netlify.app/). I opened the site in a Safari browser with the [`Shape Detection API` off](https://caniuse.com/mdn-api_barcodedetector) to ensure that the polyfill was indeed loaded and I saw no issues detecting a QR code. You can check the netlify site I hyperlinked above to see if there're any issues. If the error only happens on an aws server, it would be helpful to provide a link to that page so I can check it on my side.

**Comment by crazyrabbit0** [comment] 2024-12-01 17:12
Sadly, he AWS belongs to a client, so I can't really provide a direct link to the server right now.
I'll check if I can figure a way to provide you with a link to a problematic instance.

**Comment by crazyrabbit0** [comment] 2024-12-16 14:25
Unfortunately, I couldn't reproduce this on **Cloudflare Pages** either, I made a test [here](https://testvueqrcode.pages.dev/).

I can give you the error I get on **AWS** though:
![image](https://github.com/user-attachments/assets/bfa70beb-3108-4c9c-a2aa-87ef6c1fe2f5)


And the line it's supposed to occur:
![image](https://github.com/user-attachments/assets/67fc19a7-fef7-474a-8cc6-548aceeeb9f9)


I also noticed that the `.wasm` file is shown in the **Network Tab** only when the error occurs:
![image](https://github.com/user-attachments/assets/5f52e84a-9a0d-4098-943a-32b47c8e1dee)

**Comment by Sec-ant** [comment] 2024-12-16 15:20
@crazyrabbit0 Thanks for your effort, unfortunately I can't make anything out of the screenshot.

> I can give you the error I get on AWS though:

The error stack has very little information. The root cause was supposed to be printed along with the uncaught exception according to [this line of code](https://github.com/Sec-ant/barcode-detector/blob/526e67ed83859be41fb46bb95b94b9519e3c3c88/src/BarcodeDetector.ts#L137-L138), I wonder if there is any?

> And the line it's supposed to occur:

The minified code seems just code in `vue-qrcode-reader` where it invokes the `barcode-detector`, so it doesn't provide much information either.

> I also noticed that the .wasm file is shown in the Network Tab only when the error occurs:

The `wasm` file is lazily loaded on demand by default, so it will only be fetched on its first `detect`ion (there's a switch to change this behavior in `zxing-wasm`, but they're not exposed to `barcode-detector` or `vue-qrcode-reader` iirc). Probably this is the reason?

**Comment by crazyrabbit0** [comment] 2024-12-16 15:30
> The error stack has very little information. The root cause was supposed to be printed along with the uncaught exception according to [this line of code](https://github.com/Sec-ant/barcode-detector/blob/526e67ed83859be41fb46bb95b94b9519e3c3c88/src/BarcodeDetector.ts#L137-L138), I wonder if there is any?

Nope, nothing else is printed on console

> The `wasm` file is lazily loaded on demand by default, so it will only be fetched on its first `detect`ion (there's a switch to change this behavior in `zxing-wasm`, but they're not exposed to `barcode-detector` or `vue-qrcode-reader` iirc). Probably this is the reason?

I thought so too, but the thing is...
The Network Request doesn't show when it's working successfully with no error.

**Comment by Sec-ant** [comment] 2024-12-16 15:50
> The `wasm` file is lazily loaded on demand by default, so it will only be fetched on its first `detect`ion (there's a switch to change this behavior in `zxing-wasm`, but they're not exposed to `barcode-detector` or `vue-qrcode-reader` iirc)

My memory lied to me, the `.wasm` file is [eagerly loaded](https://github.com/Sec-ant/barcode-detector/blob/526e67ed83859be41fb46bb95b94b9519e3c3c88/src/BarcodeDetector.ts#L80-L95) in `barcode-detector` 😂.

> The Network Request doesn't show when it's working successfully with no error.

This reminds me of something... are you sure the `barcode-detector` polyfill is used when it's working successfully? Could it be using the native API provided by the browser?

**Comment by crazyrabbit0** [comment] 2024-12-16 16:33
Oooh, I'm stupid  😅
I forgot I had disabled `console & debugger` on build...


This is the actual error:
![image](https://github.com/user-attachments/assets/caf8b001-378b-49b5-94e8-858343475311)


And the line it occurs:
![image](https://github.com/user-attachments/assets/dbff8694-b0f2-4c53-bc56-2ae54eb123fa)

**Comment by Sec-ant** [comment] 2024-12-16 16:58
@crazyrabbit0 Aha, the error message is very clear now, it suggests the MIME type of the `.wasm` file is wrongly configured. The correct MIME type for it should be `application/wasm`, otherwise the browser cannot compile it. I believe this can be configured somewhere in AWS where you serve the `.wasm` file?

**Comment by crazyrabbit0** [comment] 2024-12-16 17:03
Yeah, I thought so, probably some kind of header issue.
I'll have to check with dev-ops tomorrow...

Thanks for all the help   🙏
